apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc-deployment
  labels:
    app: calc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: calc
  template:
    metadata:
      labels:
        app: calc
    spec:
      containers:
      - name: calc
        image: 193619625891.dkr.ecr.us-east-1.amazonaws.com/atharv:v2
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
      imagePullSecrets:
      - name: ecr-registry-secret
            
