apiVersion: v1
kind: Service
metadata:
  name: calc-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: calc
  ports:
    - protocol: TCP
      port: 80        # The public port exposed by the cloud load balancer
      targetPort: 8080 


